### PR TITLE
Allow multiple search in REST API

### PR DESCRIPTION
**Pull request by xxsimoxx**
Make it possible:
`https://staging-directory.classicpress.net/wp-json/wp/v2/plugins?byslug=codepotent-update-manager,icons-for-cp`

### CODE REVIEW

**Review by viktorix — APPROVED** [review]
Looks good.

**Comment by joyously** [comment]
Can you point me to the test case for single and the one for multiple?

**Comment by xxsimoxx** [comment]
This one is for multiple plugins:
`https://staging-directory.classicpress.net/wp-json/wp/v2/plugins?byslug=codepotent-update-manager,icons-for-cp`
Before this PR the search was for a plugin having `codepotent-update-manager,icons-for-cp` as slug, now is for `codepotent-update-manager` or `icons-for-cp`.
Single search is `https://staging-directory.classicpress.net/wp-json/wp/v2/plugins?byslug=codepotent-carbon-copy`.
It is to have just one query to the API to check for updates.

**Comment by joyously** [comment]
That is not a test. That is an expected usage.
I want to see a unit test that shows it works with unexpected values that hackers would send it.

**Comment by xxsimoxx** [comment]
@joyously The whole code in this repo is not covered by unit tests. 
The `meta_key` query accepts also arrays, and I've just add a `split` that makes the request an array.

**Pull request merged**
