### PR TITLE
Add plugin usage statistics

### PR DESCRIPTION
**Pull request by xxsimoxx**
As a part of the directory integration, this PR adds an `active_installation` meta value to plugins and themes.

Data is logged and then elaborated every 2 hours.
This can also forced with `wp dir regenerate_stats` command.

To have this statistic working:
- A new command was added in `wp-content/plugins/dir-cli/dir-cli.php`
- A filter is added to `wp-content/mu-plugins/rest-api.php`
- A plugin is added to the Directory to hook at that filter and do the work
- The update system must call the API using `['user-agent' => classicpress_user_agent(true)]` as `wp_remote_get` argument and `byslug=my-slug,other-slug`

### CODE REVIEW

**Comment by viktorix** [comment]
Is there a place we display them or will it be next PR? I don't think I saw anything that displays stats in this PR.

**Comment by xxsimoxx** [comment]
No, I've no added this because until we do not have an automatic update system there are no stats to display...

**Review by viktorix — APPROVED** [review]
Looks good.

**Comment by joyously** [comment]
Is this code temporary? Or does it need to have throttling for DDoS attacks?

**Comment by viktorix** [comment]
We have some built-in anti-DDoS features: Cloudflare, Litespeed server per client throttling ([few other features](https://www.litespeedtech.com/solutions/anti-ddos)), and we can enable ModSecurity if necessary.

**Pull request merged**
