### PR TITLE
Updated single software page layout

### PR DESCRIPTION
**Pull request by viktorix**
- Updated layout to include sidebar with software meta info higher on the page, so user doesn't need to scroll down to download it.
- Minor issues fixed
- Added white download icon

### CODE REVIEW

**Review by xxsimoxx — APPROVED** [review]
Like this very much!

**Comment by viktorix** [comment]
@xxsimoxx I was about to tag you to review. Please look over my PHP, just to make sure it's good. And hard refresh for CSS.

**Comment by viktorix** [comment]
I do need to fix some mobile issues.

**Comment by viktorix** [comment]
I've added repository link to the meta sidebar.

**Comment by viktorix** [comment]
Fixed mobile layout too.

**Pull request merged**
