### PR TITLE
Add items count to tabs

### LINKED ISSUE #19: Hide empty tabs on developer profiles
We should consider hiding empty tabs on developer profiles.

For example, plugins and themes would be hidden in this example:
image

### PR DESCRIPTION
**Pull request by xxsimoxx**
Closes #19.

### CODE REVIEW

**Review by viktorix — COMMENTED** [review]
@xxsimoxx what do you think about adding caching to count_user_posts()? I remember looking into it a while back since it doesn't cache results. There's a Trac ticket with some examples:
https://core.trac.wordpress.org/ticket/39242

**Comment by xxsimoxx** [comment]
Agree. But it's also something we can backport to core. I'll look next days if it can be backported quickly and if not I'll push a commit to use a transient or similar.

**Comment by viktorix** [comment]
It was never added to the core, the ticket is still open.

**Comment by xxsimoxx** [comment]
I've added cache using a transient, waiting `count_user_posts()` to cache results.

**Review by viktorix — APPROVED** [review]
Looks good to me.

**Pull request merged**
